### ISSUE TITLE
trace menu no longer works in RC14

### ISSUE THREAD

**Issue by kmun** [LGSInnovations/sigplot#68] opened 2019-07-09 17:24 UTC
**Describe the bug**
Fix to Legend that removed black box in the legend for Layer2D caused trace menu to not appear when the user presses the left mouse button.  Works fine with single trace sigplots.

**To Reproduce**

Create 2D trace with more than one trace.
Press L in upper right
Press  left mouse button
Should see a menu pop up to allow user to turn on/off trace or change thickness etc..  But it doesn't show up.

**Comment by kmun** [comment] 2019-07-09 20:44
Update:  I changed the name on the issue but left the original bug report as is.  The trace menu does come up if you put your cursor on the extension of the filename so if it's a 4 element file the legend will show
(green bar) filename.001
(blue bar) filename.002
(red  bar) filename.003
(yellow bar) filename.004

If you put your cursor on the 001/002/003/004 and left mouse click, the menu does come up.  So there is a workaround; or perhaps that's how it is supposed to work.

**Comment by maihde** [comment] 2019-07-09 23:06
@kmun I'm not able to reproduce this with RC14.

Here are the steps that I'm doing to try and reproduce the issue.

1) `grunt` to build SigPlot from `master`
2) `grunt web_server` to start the unittesting environment
3) Open a web-browser to http://localhost:1337
4) Execute test `sigplot-interactive: sigplot penny 1d legend default`
5) Follow the steps you suggested above

In my test the trace options turns on when I click anywhere on the filename or trace "bar".  Can you try to run the unittests yourself and describe the behavior you are seeing?

Perhaps the difference in behavior is due to browser differences.  What browser environment are you using?

**Comment by mrecachinas** [comment] 2020-02-24 21:43
@kmun It's been a few months with no reply, so I'm going to close this issue. If you're still having issues, please re-open or submit a new issue.

**Closed by mrecachinas** 2020-02-24 21:43 UTC
