### ISSUE TITLE
Black rectangle in legend

### ISSUE THREAD

**Issue by kmun** [LGSInnovations/sigplot#55] opened 2019-07-03 14:13 UTC
**Describe the bug**
When displaying a type 2000 file in 1D mode there is a black rectangle in the left side of the legend

**To Reproduce**

Create a plot
Set the Layer type as 1D  (sigplot.Layer1D)
Plot a type 2000 file using overlay
Verify each element in the 2000 file is displayed, i.e. if it's 4 deep that 4 color traces appear
Press the L in the upper right corner
Verify that all the elements are indicated in the legend with a .001,.002 suffix.
See that  there is a black rectangle in the left side of the legend covering the first part of the name of the file.  The rectangle gets taller as there are more entries.  Around the first 8 characters of the names are covered, as well as the colored lines.  IF YOU TOGGLE OFF all of the elements in the file, the black rectangle goes away.  Toggling back on one of the elements makes the rectangle reappear.

**Expected behavior**
See that  there is a black rectangle in the left side of the legend covering the first part of the name of the file.  This is NOT shown in the penny.prm file on the sigplot web site under:

https://sigplot.lgsinnovations.com/sigplot-2.0/inaction.html

where it is a 1D representation of 2D data. 

**jsFiddle**

None

**Screenshots**
None

**Desktop (please complete the following information):**
Same results with Microsoft Edge and Firefox

**Smartphone (please complete the following information):**
None

**Additional context**
None

**Comment by maihde** [comment] 2019-07-03 21:47
Thanks.  I can confirm that I am able to reproduce this issue and will get it fixed soon.

**Comment by maihde** [comment] 2019-07-04 14:49
@kmun This bug was introduced in ef66bc51347408191696c3daf683681d7e953485.

Basically there were three issues:
1) the code incorrectly used the header class instead of looking at the layer type to determine if the line or color bar should be draw
2) the code didn't draw the color bar in the legend correctly due to a  typo, so it instead drew a blank box
3) the colorbar legend box was not scaled correctly if there was more than one layer present.

After the fix I'm committing, things all look good.

![image](https://user-images.githubusercontent.com/229922/60674889-290c8b80-9e49-11e9-9312-77be5a1f9b3c.png)

![image](https://user-images.githubusercontent.com/229922/60674908-3295f380-9e49-11e9-974b-b8282d0484fe.png)

**Comment by mrecachinas** [comment] 2019-07-05 15:33
Fixed in 4082976 (#58).

**Closed by mrecachinas** 2019-07-05 15:33 UTC
